
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'rdd_merlin'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  rdd_merlin:
    sagai:
      # Applies to all files under models/example/
      staging:
        +materialized: view
        +schema: rdd_stagging
      cleaned:
        +materialized: table
        +schema: rdd_cleaned      
      intermediate:
        +materialized: table
        +schema: rdd_intermediate      
      export:
        +materialized: table
        +schema: rdd_export
      analysed:
        +materialized: view
        +schema: rdd_analysed                   
    mapping:
      +materialized: view
      +schema: rdd_mapping
    externe:
      +materialized: view
      +schema: rdd_externe